create database customer_behavior;
use customer_behavior;
select * from customer;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchased_amount) as revenue_generated
 from customer
 group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
-- select customer_id from customer where customer_id=1132;-- 
SELECT customer_id,
       SUM(purchased_amount) AS total_spent
FROM customer
WHERE discount_applied = 'yes'
GROUP BY customer_id
HAVING SUM(purchased_amount) > (
    SELECT AVG(purchased_amount) FROM customer
);
-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(cast(review_rating as decimal)),2) as average_review_rating 
from customer group by item_purchased
order by average_review_rating desc limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select round(avg(purchased_amount),2) as average_amount,shipping_type 
from customer
 where shipping_type in ("Standard","Express") 
 group by  shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select count(customer_id) as total_customer,round(sum(purchased_amount),2) as total_spent,
round(avg(purchased_amount),2) as average_spent,subscription_status
 from customer
 group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, sum(case when discount_applied="yes" then 1 else 0 end)/count(item_purchased)*100 as percentage_of_purchases
 from customer
 group by item_purchased 
 order by percentage_of_purchases desc 
 limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as (
select previous_purchases,
case 
when previous_purchases = 1 then "new"
when previous_purchases between 2 and 10 then "returning"
else "loyal"
end as customer_segment
from customer)
select count(*) as no_of_customers,customer_segment
from customer_type 
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
SELECT * from(select item_purchased, category, count(customer_id) as frequency,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as rn
from customer group by category,item_purchased) t

where rn<=3; 
 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(customer_id) as repeated_buyers,subscription_status
from customer 
where previous_purchases>5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchased_amount) as revenue_contribution
from customer group by age_group order by revenue_contribution desc;
